spring:
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB
  tomcat:
    max-swallow-size: -1

  main:
    banner-mode: OFF

  datasource:
    url: url
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  jackson:
    time-zone: UTC
    date-format: dd-MM-yyyy HH:mm:ss

server:
  port: 8080

logging:
  config: classpath:logback-spring.xml

app:
  async:
    core-pool-size: 5
    max-pool-size: 20
    queue-capacity: 100
  retry:
    max-attempts: 3
    delay: 1000
  scheduler:
    enabled: true

telegram:
  bot:
    name: "@name"
    token: "token"

ppk:
  schedule-link: "link"